pipeline {

    agent any

    stages {

        stage('Running scan') {

            option {
                timeout(time: 10, unit: 'MINUTES')
            }

            steps {
                git 'https://github.com/capstone-project-cybersecurity/automate-scan.git'
                sh 'docker build -t automate-scan'
                sh 'docker run automate-scan'
            }
        }
    }
            post {
                sucess {
                    sh 'echo "All good!!!"'
                }
            }
}